### ISSUE TITLE
ming 0.9.1 requirements pymongo < 3.8

### ISSUE THREAD

**Issue by yaniv-ms** [TurboGears/Ming#12]
Hello,

I'd like to know if there's a reason ming 0.9.1 requires pymongo < 3.8 and not <= 3.8, was there a problem running ming with pymongo 3.8.0 or was it only not tested?

I'm willing to help if there's anything I can do to fix/test ming support with pymongo 3.8.0. 

Thank you,

Yaniv

**Comment by brondsem** [comment]
The `<3.8` version specifier was done in #11 and looks to me like it was supporting the latest at the time.  So probably just 3.8 wasn't available or tested yet.  The pymongo 3.8 [changelog](http://api.mongodb.com/python/current/changelog.html) doesn't mention any breaking changes, so it may work fine.  If you want to try testing ming with pymongo 3.8 and report your findings that sounds like a good next step.

**Comment by yaniv-ms** [comment]
Sure, I'd like to help.

Is there a document of how to contribute? How to install the environment, run the tests, etc.

**Comment by amol-** [comment]
We are constrained to 3.7 only because we don't want new releases that happen to be automatically installed without having the chance to verify that Ming works with them (the most frequent case is that MongoInMemory breaks on pymongo changes). 

3.8 wasn't yet a thing when the last Ming release happened and thus wasn't tested against it.

If you want to test ming locally, you can just clone the repository and run `tox` to setup ming and run tests. If you wish to contribute a "how to contribute" section to https://ming.readthedocs.io/en/latest/ with the result of your experience trying to get ming working for you I think that would be absolutely great!
