### ISSUE TITLE
Pymongo Dependency support of later versions - 3.10

### ISSUE THREAD

**Issue by pgmustard-admin** [TurboGears/Ming#16]
Hi,

We have been advised by MongoDB that we are hitting a condition in the Pymongo code that doesnt recover from instance failover's very well and that we need to upgrade from Pymongo 3.6 to Pymongo 3.10.

Unfortunately, ming, does not yet support PyMongo as far back as 3.8 
https://github.com/TurboGears/Ming/blob/master/setup.py#L38.

This dependency is also preventing us from upgrading our MongoDB Cluster.

Are there any plans to move this dependency forward? I can see a similar issue was raised for version 3.8 support  (https://github.com/TurboGears/Ming/issues/12)

Thanks in advance

**Comment by amol-** [comment]
The problem is mostly with newer session management for transactions that needs to get proper support in Ming. Possibly enabling usage of transactions too. I have a local branch with work ongoing for that, but it's far from being done.

On the other side we could probably support pymongo3.8 and 3.10 out of the box if we ignore support for sessions. I pushed branch with the minimum required changes (mostly MIM) to work with pymongo3.10 -> https://github.com/TurboGears/Ming/tree/pymongo310

If @brondsem has a chance to run the allura test suite with that branch (and pymongo3.10) and confirm that things are working as epxected for him too I think it's reasonable to ship it.

**Comment by pgmustard-admin** [comment]
Hi,

interesting - so potentially provide stop gap basic feature support for 3.10 while session management for transactions is worked on?

that would definitely help in the short term.

Thanks again.

**Comment by brondsem** [comment]
Allura isn't using latest ming right now, so has a few minor-looking errors just by using master branch of ming, and pymongo.  Also the Allura test suite uses mim entirely, so isn't a complete test.  The pymongo310 branch with pymongo 3.10 gets mostly the same errors so I think it's probably fine?  One of the errors is with mim and pymongo 3.8, I'll make a separate issue for it.  Not sure about other errors yet (could be Allura problems)

I did notice `setup.py` has `pymongo>=3.0,<3.12` but should be `<3.11` right?

I'll post again if/when I get a chance to do any testing with real mongo instead of mim.

**Comment by pgmustard-admin** [comment]
Hi @brondsem 

any luck with this? 

we confirmed with MongoDB that a bug in pymongo is causing our outages everytime a mongo cluster election happens..

some context of the issue from MongoDB:

> You are correct that remove_stale_sockets appears to be the cause of the exception. Unfortunately in the version of PyMongo you are running, it incorrectly holds a lock while reestablishing a connection after a pool reset. The issue is racy in nature, which is why you would not see it happen consistently.
> The issue is fixed in in PYTHON-1954, therefore we recommend that you upgrade to the latest version being 3.10.1.

Thanks

**Comment by brondsem** [comment]
Hi,

I haven't had time to do any further testing, but I don't think that needs to hold this up.  Have you tried testing the pymongo310 branch with your app to see if it works for you?

Otherwise I don't expect there to be any significant problems (the pymongo changelog doesn't have any major changes that I expect would impact ming).  And if minor issues arise later, we can always do followup fixes.

**Comment by amol-** [comment]
I'm merging the pymongo310 branch into master with some extra changes:

1. the testsuite now doesn't need `nose` anymore as it shortly stop working
2. moving from nose to unittest discover showcased and error in how the tests were registering the mapper and in general `Mapper.clear_all` wasn't exactly working.
3. Avoid registering a mapper for `MappedClass` itself, the fix to `Mapper.clear_call` exposed that we were registering it too.

**Comment by pgmustard-admin** [comment]
Brill thanks @amol and @brondsem
